package top.tsep.dao;

import org.apache.ibatis.annotations.Param;

import top.tsep.pojo.UserEntity;

public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int insertSelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    UserEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserEntity record);
    
    
    int insertUserSubject(@Param("userId")int userId,@Param("subjectId")int subjectId);
    
    
    UserEntity checkLogin(UserEntity record);
    
}