package top.tsep.pojo;

public class UserEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.user_type
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.user_tx
     *
     * @mbggenerated
     */
    private String userTx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.pass_word
     *
     * @mbggenerated
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.user_qq
     *
     * @mbggenerated
     */
    private String userQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.user_intro
     *
     * @mbggenerated
     */
    private String userIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.attribute1
     *
     * @mbggenerated
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.attribute2
     *
     * @mbggenerated
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.attribute3
     *
     * @mbggenerated
     */
    private String attribute3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.id
     *
     * @return the value of ts_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.id
     *
     * @param id the value for ts_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.nick_name
     *
     * @return the value of ts_user.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.nick_name
     *
     * @param nickName the value for ts_user.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.real_name
     *
     * @return the value of ts_user.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.real_name
     *
     * @param realName the value for ts_user.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.email
     *
     * @return the value of ts_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.email
     *
     * @param email the value for ts_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.user_type
     *
     * @return the value of ts_user.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.user_type
     *
     * @param userType the value for ts_user.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.user_tx
     *
     * @return the value of ts_user.user_tx
     *
     * @mbggenerated
     */
    public String getUserTx() {
        return userTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.user_tx
     *
     * @param userTx the value for ts_user.user_tx
     *
     * @mbggenerated
     */
    public void setUserTx(String userTx) {
        this.userTx = userTx == null ? null : userTx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.pass_word
     *
     * @return the value of ts_user.pass_word
     *
     * @mbggenerated
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.pass_word
     *
     * @param passWord the value for ts_user.pass_word
     *
     * @mbggenerated
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.user_qq
     *
     * @return the value of ts_user.user_qq
     *
     * @mbggenerated
     */
    public String getUserQq() {
        return userQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.user_qq
     *
     * @param userQq the value for ts_user.user_qq
     *
     * @mbggenerated
     */
    public void setUserQq(String userQq) {
        this.userQq = userQq == null ? null : userQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.user_intro
     *
     * @return the value of ts_user.user_intro
     *
     * @mbggenerated
     */
    public String getUserIntro() {
        return userIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.user_intro
     *
     * @param userIntro the value for ts_user.user_intro
     *
     * @mbggenerated
     */
    public void setUserIntro(String userIntro) {
        this.userIntro = userIntro == null ? null : userIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.create_time
     *
     * @return the value of ts_user.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.create_time
     *
     * @param createTime the value for ts_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.user_phone
     *
     * @return the value of ts_user.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.user_phone
     *
     * @param userPhone the value for ts_user.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.attribute1
     *
     * @return the value of ts_user.attribute1
     *
     * @mbggenerated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.attribute1
     *
     * @param attribute1 the value for ts_user.attribute1
     *
     * @mbggenerated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.attribute2
     *
     * @return the value of ts_user.attribute2
     *
     * @mbggenerated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.attribute2
     *
     * @param attribute2 the value for ts_user.attribute2
     *
     * @mbggenerated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.attribute3
     *
     * @return the value of ts_user.attribute3
     *
     * @mbggenerated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.attribute3
     *
     * @param attribute3 the value for ts_user.attribute3
     *
     * @mbggenerated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }
}